Disallow running under root.

diff --git a/norm b/norm
--- a/norm
+++ b/norm
@@ -24,6 +24,8 @@ perl ' use v5.10.0; ' 2>/dev/null || CONFIGURE_FILTER=cat
 
 newprefix=$DEFAULT_PREFIX
 
+[ $UID == "0" ] && log "Error: I will not run for root user." && exit 1
+
 usage() {
     echo "Usage:"
     echo "    $OURNAME install <package> [package ...]   -- install package(s)"
