move c compiler sanity check inside `norm install`

diff --git a/norm b/norm
--- a/norm
+++ b/norm
@@ -18,12 +18,6 @@ export LANG=C LC_ALL=C
 ## root users must use distro's package manager
 [ $EUID == "0" ] && log "Error: I will not run for root user." && exit 1
 
-## cc sanity check
-if ! test_cc_func "stdio.h" 'printf("Hello, world!\n");'; then
-    log "Error: your compiler can't compile!"
-    log "Check that your have it installed correctly"
-    exit 1
-fi
 
 ## curl availability check
 unset DOWNLOADER
@@ -65,6 +59,12 @@ usage() {
 }
 
 cmd_install() {
+    ## cc sanity check
+    if ! test_cc_func "stdio.h" 'printf("Hello, world!\n");'; then
+        log "Error: your compiler can't compile!"
+        log "Check that your have it installed correctly"
+        exit 1
+    fi
     local force
     norm_keep_sources=
     while getopts "fkv" opt; do
